//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public Computer()
        {
            this.Harddrives = new HashSet<Harddrive>();
            this.Motherboards = new HashSet<Motherboard>();
            this.OperatingSystems = new HashSet<OperatingSystem>();
            this.Processors = new HashSet<Processor>();
            this.RAMs = new HashSet<RAM>();
        }
    
        public int ComputerID { get; set; }
        public string Name { get; set; }
        public string FormFactor { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string PrimaryMac { get; set; }
    
        public virtual ICollection<Harddrive> Harddrives { get; set; }
        public virtual ICollection<Motherboard> Motherboards { get; set; }
        public virtual ICollection<OperatingSystem> OperatingSystems { get; set; }
        public virtual ICollection<Processor> Processors { get; set; }
        public virtual ICollection<RAM> RAMs { get; set; }
    }
}
