//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harddrive
    {
        public int HarddriveID { get; set; }
        public string Type { get; set; }
        public int Capacity { get; set; }
        public int ComputerID { get; set; }
    
        public virtual Computer Computer { get; set; }
    }
}
