//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboard
    {
        public int MotherboardID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> NumberOfDisplayPorts { get; set; }
        public Nullable<int> NumberOfMemoryPorts { get; set; }
        public bool HasParallelPort { get; set; }
        public int ComputerID { get; set; }
    
        public virtual Computer Computer { get; set; }
    }
}
